### ISSUE TITLE
Going "back" inside a yew application doesn't trigger a rerender

### ISSUE THREAD

**Issue by aDogCalledSpot** [ctron/yew-nested-router#13]
Steps to reproduce:

1. Visit https://patternfly-yew.github.io/patternfly-yew-quickstart/
1. Navigate anywhere
1. Click "back" in your browser

Result:The URL changes but the page stays the same

Expected result: I return to the home page

**Comment by ctron** [comment]
Yikes … that's probably an issue with the event handling.

**Comment by ctron** [comment]
Fixed, also in the quickstart.
