### ISSUE TITLE
have a "default" macro for `Target` enums

### ISSUE THREAD

**Issue by jbtrystram** [ctron/yew-nested-router#2]
```rust
#[derive(Clone, Debug, PartialEq, Eq, Target)]
pub enum Details {
  Overview,
  Code,
  Metrics,
}

impl Default for Details {
  fn default() -> Self {
    Self::Overview
  }
}
```

Could be 
```rust
#[derive(Clone, Debug, PartialEq, Eq, Target)]
pub enum Details {
#[target(default)]
  Overview,
  Code,
  Metrics,
}
```

I know `#[target(default)]` is already a thing :D names are hard

**Comment by ctron** [comment]
You can use the new `default` attribute from Rust. However, that comes with Rust 1.62 (?). And I wanted to keep the MSRV at the same level as Yew has it (1.60).

So, you already can do:

```rust
#[derive(Clone, Debug, Default, ParrtialEq, Eq, Target)]
pub enum Details {
  #[default]
  Overview,
  Code,
  Metrics,
}
```

But only if you use a newer Rust version.

**Comment by ctron** [comment]
Forgot about this one, I think we can close it.
